language: "perl"
perl:
  - "5.22"
#  - "5.20"
#  - "5.18"
#  - "5.16"
#  - "5.14"
#  - "5.12"
before_install:
#  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
#  - source ~/travis-perl-helpers/init --auto
  - sudo apt-get -qq update
  - sudo apt-get -y install libmojolicious-perl libauthen-passphrase-perl libdbd-mysql-perl libdbi-perl libdbix-connector-perl libipc-run3-perl libnet-ldap-perl libproc-pid-file-perl libxml-libxml-perl libconfig-yaml-perl libmoose-perl libjson-xs-perl qemu-utils perlmagick libmoosex-types-netaddr-ip-perl libio-interface-perl libnet-dns-perl wget liblocale-maketext-lexicon-perl libmojolicious-plugin-i18n-perl libdbd-sqlite3-perl
  - git clone https://github.com/frankiejol/Test-SQL-Data.git ~/Test-SQL-Data
  - cd ~/Test-SQL-Data
  - perl Makefile.PL
  - make install
  - cd -
script: "perl Makefile.PL && make test"
# branches:
#   only:
#     - master
#env:
#group: "stable"
group: edge
#dist: "zesty"
#dist: "yakkety"
#sudo: required
#sudo: false
dist: trusty
